using OneOf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HaloScriptPreprocessor.AST
{
    class Atom : INode
    {
        private OneOf<Parser.ExpressionParser.Atom, string> _value;
        public OneOf<Parser.ExpressionParser.Atom, string> Value {
            get => _value;
            set
            {
                _value = value;
                _modified = true;
            }
        }

        /// <summary>
        /// Was the atom value created by the parser?
        /// </summary>
        public bool IsFromParser
        {
            get => Value.IsT0;
        }

        /// <summary>
        /// Was the atom value generated by a pass? 
        /// </summary>
        public bool IsGenerated
        {
            get => Value.IsT1;
        }

        private bool _modified;

        /// <summary>
        /// Was the value modified after creation?
        /// </summary>
        public bool IsModified
        {
            get => _modified;
        }

        public uint NodeCount => 1;
    }
}
